source 'https://rubygems.org'

gem 'soda-ruby', :require => 'soda'
gem 'sqlite3', '~> 1.3.8'
gem 'ruby-oci8', '~> 2.1.5'
gem 'sequel', '~> 4.0.0'
gem 'json'
gem 'configatron' 
gem 'hashie'
gem 'httparty'
gem 'jsonpath'
gem 'activerecord'
gem 'nokogiri'
gem 'crack'
gem 'icalendar'
gem 'seeclickfix'
gem 'actionpack', '~> 4.2.0'
gem 'rest_client'
gem 'normalic'